### ISSUE TITLE
Basic setup

### ISSUE THREAD

**Issue by tech4GT** [nsITians/RMT_Backend#1]
The basic server is now setup and we can now start with some frontend development
@lakshay365 @gabru-md

**Comment by gabru-md** [comment]
cool, I'll set up a very basic react application for the same in the other repository so that we can begin the work over there as well

**Comment by lakshay365** [comment]
I have already set up a React App and I am working on the front page right now.

**Comment by tech4GT** [comment]
@lakshay365 let me know if you need something on the backend

**Comment by lakshay365** [comment]
A basic react app with just homepage is implemented. See https://github.com/nsITians/rate.nsut.me/commit/c5310a3c8d0e1ce52c1988dd38335998c3253134 for more details.
